// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// IP-based access rules for the Managed Lustre instance. These options
/// define the root user squash configuration.
public struct AccessRulesOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The access rules for the instance.
  public var accessRules: [AccessRulesOptions.AccessRule] = []

  /// Required. The squash mode for the default access rule.
  public var defaultSquashMode: AccessRulesOptions.SquashMode = AccessRulesOptions.SquashMode()

  /// Optional. The user squash UID for the default access rule.
  /// This user squash UID applies to all root users connecting from clients
  /// that are not matched by any of the access rules. If not set, the default
  /// is 0 (no UID squash).
  public var defaultSquashUid: Swift.Int32 = Swift.Int32()

  /// Optional. The user squash GID for the default access rule.
  /// This user squash GID applies to all root users connecting from clients
  /// that are not matched by any of the access rules. If not set, the default
  /// is 0 (no GID squash).
  public var defaultSquashGid: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccessRulesOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessRulesOptions().with { $0.accessRules = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accessRules = CodingKeys(stringValue: "accessRules")
    static let defaultSquashMode = CodingKeys(stringValue: "defaultSquashMode")
    static let defaultSquashUid = CodingKeys(stringValue: "defaultSquashUid")
    static let defaultSquashGid = CodingKeys(stringValue: "defaultSquashGid")

    static let _knownKeys: Set<Swift.String> = [
      "accessRules",
      "defaultSquashMode",
      "defaultSquashUid",
      "defaultSquashGid",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [AccessRulesOptions.AccessRule].self, forKey: .accessRules)
    {
      self.accessRules = value
    }
    if let value = try container.decodeIfPresent(
      AccessRulesOptions.SquashMode.self, forKey: .defaultSquashMode)
    {
      self.defaultSquashMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .defaultSquashUid) {
      self.defaultSquashUid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .defaultSquashGid) {
      self.defaultSquashGid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accessRules, forKey: .accessRules)
    try container.encode(self.defaultSquashMode, forKey: .defaultSquashMode)
    try container.encode(self.defaultSquashUid, forKey: .defaultSquashUid)
    try container.encode(self.defaultSquashGid, forKey: .defaultSquashGid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A single policy group with IP-based access rules for the Managed
  /// Lustre instance.
  public struct AccessRule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The name of the access rule policy group.
    /// Must be 16 characters or less and include only alphanumeric characters
    /// or '_'.
    public var name: Swift.String = Swift.String()

    /// Required. The IP address ranges to which to apply this access rule.
    /// Accepts non-overlapping CIDR ranges (e.g., `192.168.1.0/24`) and IP
    /// addresses (e.g., `192.168.1.0`).
    public var ipAddressRanges: [Swift.String] = []

    /// Required. Squash mode for the access rule.
    public var squashMode: AccessRulesOptions.SquashMode = AccessRulesOptions.SquashMode()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AccessRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AccessRule().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let ipAddressRanges = CodingKeys(stringValue: "ipAddressRanges")
      static let squashMode = CodingKeys(stringValue: "squashMode")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "ipAddressRanges",
        "squashMode",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipAddressRanges) {
        self.ipAddressRanges = value
      }
      if let value = try container.decodeIfPresent(
        AccessRulesOptions.SquashMode.self, forKey: .squashMode)
      {
        self.squashMode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.ipAddressRanges, forKey: .ipAddressRanges)
      try container.encode(self.squashMode, forKey: .squashMode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.lustre.v1.AccessRulesOptions.AccessRule"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Squash mode for an access rule.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SquashMode: Codable, Equatable, Hashable, Sendable {
    /// Unspecified squash mode.
    case unspecified
    /// Squash is disabled.
    ///
    /// If set inside an
    /// [AccessRule][google.cloud.lustre.v1.AccessRulesOptions.AccessRule], root
    /// users matching the [ip_ranges][AccessRule.ip_ranges] are not squashed.
    ///
    /// If set as the
    /// [default_squash_mode][google.cloud.lustre.v1.AccessRulesOptions.default_squash_mode],
    /// root squash is disabled for this instance.
    ///
    /// If the default squash mode is `NO_SQUASH`, do not set the
    /// [default_squash_uid][google.cloud.lustre.v1.AccessRulesOptions.default_squash_uid]
    /// or
    /// [default_squash_gid][google.cloud.lustre.v1.AccessRulesOptions.default_squash_gid],
    /// or an `invalid argument` error is returned.
    ///
    /// [google.cloud.lustre.v1.AccessRulesOptions.AccessRule]: <doc:AccessRulesOptions/AccessRule>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_gid]: <doc:AccessRulesOptions/defaultSquashGid>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_mode]: <doc:AccessRulesOptions/defaultSquashMode>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_uid]: <doc:AccessRulesOptions/defaultSquashUid>
    case noSquash
    /// Root user squash is enabled.
    ///
    /// Not supported inside an
    /// [AccessRule][google.cloud.lustre.v1.AccessRulesOptions.AccessRule].
    ///
    /// If set as the
    /// [default_squash_mode][google.cloud.lustre.v1.AccessRulesOptions.default_squash_mode],
    /// root users not matching any of the
    /// [access_rules][google.cloud.lustre.v1.AccessRulesOptions.access_rules]
    /// are squashed to the
    /// [default_squash_uid][google.cloud.lustre.v1.AccessRulesOptions.default_squash_uid]
    /// and
    /// [default_squash_gid][google.cloud.lustre.v1.AccessRulesOptions.default_squash_gid].
    ///
    /// [google.cloud.lustre.v1.AccessRulesOptions.AccessRule]: <doc:AccessRulesOptions/AccessRule>
    /// [google.cloud.lustre.v1.AccessRulesOptions.access_rules]: <doc:AccessRulesOptions/accessRules>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_gid]: <doc:AccessRulesOptions/defaultSquashGid>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_mode]: <doc:AccessRulesOptions/defaultSquashMode>
    /// [google.cloud.lustre.v1.AccessRulesOptions.default_squash_uid]: <doc:AccessRulesOptions/defaultSquashUid>
    case rootSquash
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noSquash: return 1
      case .rootSquash: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SQUASH_MODE_UNSPECIFIED"
      case .noSquash: return "NO_SQUASH"
      case .rootSquash: return "ROOT_SQUASH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SquashMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SQUASH_MODE_UNSPECIFIED": self = .unspecified
      case "NO_SQUASH": self = .noSquash
      case "ROOT_SQUASH": self = .rootSquash
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SquashMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noSquash
      case 2: self = .rootSquash
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SQUASH_MODE_UNSPECIFIED")
      case .noSquash: return try container.encode("NO_SQUASH")
      case .rootSquash: return try container.encode("ROOT_SQUASH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.AccessRulesOptions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
