// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for importing data to Lustre.
public struct ImportDataRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Managed Lustre instance in the format
  /// `projects/{project}/locations/{location}/instances/{instance}`.
  public var name: Swift.String = Swift.String()

  /// Optional. UUID to identify requests.
  public var requestId: Swift.String = Swift.String()

  /// Optional. User-specified service account used to perform the transfer.
  /// If unspecified, the default Managed Lustre service agent will be used.
  ///
  /// Use one of the following formats:
  ///
  /// * `{EMAIL_ADDRESS_OR_UNIQUE_ID}`
  /// * `projects/{PROJECT_ID}/serviceAccounts/{EMAIL_ADDRESS_OR_UNIQUE_ID}`
  /// * `projects/-/serviceAccounts/{EMAIL_ADDRESS_OR_UNIQUE_ID}`
  public var serviceAccount: Swift.String = Swift.String()

  /// A Cloud Storage URI of a folder to import file data from, in the
  /// form of `gs://<bucket_name>/<path_inside_bucket>/`.
  public var source: SourceOneOf? = nil

  /// The destination of the data transfer.
  public var destination: DestinationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportDataRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportDataRequest().with { $0.gcsPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsPath = CodingKeys(stringValue: "gcsPath")
    static let lustrePath = CodingKeys(stringValue: "lustrePath")
    static let name = CodingKeys(stringValue: "name")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")

    static let _knownKeys: Set<Swift.String> = [
      "gcsPath",
      "lustrePath",
      "name",
      "requestId",
      "serviceAccount",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }

    var source: SourceOneOf? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsPath = try container.decodeIfPresent(GcsPath.self, forKey: .gcsPath) {
      try sourceCheckAndSet(.gcsPath(gcsPath))
    }
    self.source = source

    var destination: DestinationOneOf? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let lustrePath = try container.decodeIfPresent(LustrePath.self, forKey: .lustrePath) {
      try destinationCheckAndSet(.lustrePath(lustrePath))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)

    if let choice = self.source {
      switch choice {
      case .gcsPath(let value):
        try container.encode(value, forKey: .gcsPath)
      }
    }

    if let choice = self.destination {
      switch choice {
      case .lustrePath(let value):
        try container.encode(value, forKey: .lustrePath)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A Cloud Storage URI of a folder to import file data from, in the
  /// form of `gs://<bucket_name>/<path_inside_bucket>/`.
  public enum SourceOneOf: Codable, Equatable, Sendable {
    /// The Cloud Storage source bucket and, optionally, path inside the bucket.
    /// If a path inside the bucket is specified, it must end with a forward
    /// slash (`/`).
    indirect case gcsPath(GcsPath)
  }

  /// The destination of the data transfer.
  public enum DestinationOneOf: Codable, Equatable, Sendable {
    /// Lustre path destination.
    indirect case lustrePath(LustrePath)
  }

  /// The type URL for `ImportDataRequest`: `"type.googleapis.com/google.cloud.lustre.v1.ImportDataRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.ImportDataRequest"
  }

  /// Initialize an instance of `ImportDataRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.ImportDataRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ImportDataRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
