// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Managed Lustre instance.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the instance.
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The filesystem name for this instance. This name is
  /// used by client-side tools, including when mounting the instance. Must be
  /// eight characters or less and can only contain letters and numbers.
  public var filesystem: Swift.String = Swift.String()

  /// Required. The storage capacity of the instance in gibibytes (GiB). Allowed
  /// values depend on the `perUnitStorageThroughput`. See [Performance
  /// tiers](https://docs.cloud.google.com/managed-lustre/docs/performance-tiers)
  /// for specific minimums, maximums, and step sizes for each performance tier.
  public var capacityGib: Swift.Int64 = Swift.Int64()

  /// Required. Immutable. The full name of the VPC network to which the instance
  /// is connected. Must be in the format
  /// `projects/{project_id}/global/networks/{network_name}`.
  public var network: Swift.String = Swift.String()

  /// Output only. The state of the instance.
  public var state: Instance.State = Instance.State()

  /// Output only. Mount point of the instance in the format
  /// `IP_ADDRESS@tcp:/FILESYSTEM`.
  public var mountPoint: Swift.String = Swift.String()

  /// Output only. Timestamp when the instance was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when the instance was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. A user-readable description of the instance.
  public var description: Swift.String = Swift.String()

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The throughput of the instance in MBps per TiB. Valid values are
  /// 0, 125, 250, 500, 1000. See [Performance
  /// tiers](https://docs.cloud.google.com/managed-lustre/docs/performance-tiers)
  /// for more information.
  ///
  /// If the instance is using the Dynamic tier, this field must not be set or
  /// must be set to zero.
  public var perUnitStorageThroughput: Swift.Int64 = Swift.Int64()

  /// Optional. Deprecated: No longer required for GKE instance creation.
  /// Indicates whether you want to enable support for GKE clients. By default,
  /// GKE clients are not supported.
  @available(*, deprecated)
  public var gkeSupportEnabled: Swift.Bool = Swift.Bool()

  /// Optional. Immutable. The Cloud KMS key name to use for data encryption.
  /// If not set, the instance will use Google-managed encryption keys.
  /// If set, the instance will use customer-managed encryption keys.
  /// The key must be in the same region as the instance.
  /// The key format is:
  /// projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{key}
  public var kmsKey: Swift.String = Swift.String()

  /// Output only. The reason why the instance is in a certain state (e.g.
  /// SUSPENDED).
  public var stateReason: Swift.String = Swift.String()

  /// Optional. The placement policy name for the instance in the format of
  /// projects/{project}/locations/{location}/resourcePolicies/{resource_policy}
  public var placementPolicy: Swift.String = Swift.String()

  /// Optional. The access rules options for the instance.
  public var accessRulesOptions: AccessRulesOptions? = nil

  /// Output only. Unique ID of the resource.
  /// This is unrelated to the access rules which allow specifying the root
  /// squash uid.
  public var uid: Swift.String = Swift.String()

  /// Optional. The maintenance policy for the instance to determine when to
  /// allow or exclude the instance from maintenance updates.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. Date and time of upcoming maintenance for the instance, if a
  /// maintenance policy is set.
  public var upcomingMaintenanceSchedule: MaintenanceSchedule? = nil

  /// Optional. Immutable. Specifies whether the instance is on the Dynamic tier.
  /// See [Performance
  /// tiers](https://docs.cloud.google.com/managed-lustre/docs/performance-tiers)
  /// for more information.
  public var dynamicTierOptions: DynamicTierOptions? = nil

  /// Output only. The available version that this instance can be upgraded to.
  /// Format: `Lustre_YYYYMMDD.NN_pXX`
  public var availableVersion: Swift.String? = nil

  /// Optional. The target version of the instance. Setting this field triggers a
  /// self-service update to the specified version.
  /// Format: `Lustre_YYYYMMDD.NN_pXX` or `latest`
  public var targetVersion: Swift.String? = nil

  /// Output only. The effective version of the instance.
  /// Format: `Lustre_YYYYMMDD.NN_pXX`
  public var effectiveVersion: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let filesystem = CodingKeys(stringValue: "filesystem")
    static let capacityGib = CodingKeys(stringValue: "capacityGib")
    static let network = CodingKeys(stringValue: "network")
    static let state = CodingKeys(stringValue: "state")
    static let mountPoint = CodingKeys(stringValue: "mountPoint")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let perUnitStorageThroughput = CodingKeys(stringValue: "perUnitStorageThroughput")
    static let gkeSupportEnabled = CodingKeys(stringValue: "gkeSupportEnabled")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let stateReason = CodingKeys(stringValue: "stateReason")
    static let placementPolicy = CodingKeys(stringValue: "placementPolicy")
    static let accessRulesOptions = CodingKeys(stringValue: "accessRulesOptions")
    static let uid = CodingKeys(stringValue: "uid")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let upcomingMaintenanceSchedule = CodingKeys(stringValue: "upcomingMaintenanceSchedule")
    static let dynamicTierOptions = CodingKeys(stringValue: "dynamicTierOptions")
    static let availableVersion = CodingKeys(stringValue: "availableVersion")
    static let targetVersion = CodingKeys(stringValue: "targetVersion")
    static let effectiveVersion = CodingKeys(stringValue: "effectiveVersion")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "filesystem",
      "capacityGib",
      "network",
      "state",
      "mountPoint",
      "createTime",
      "updateTime",
      "description",
      "labels",
      "perUnitStorageThroughput",
      "gkeSupportEnabled",
      "kmsKey",
      "stateReason",
      "placementPolicy",
      "accessRulesOptions",
      "uid",
      "maintenancePolicy",
      "upcomingMaintenanceSchedule",
      "dynamicTierOptions",
      "availableVersion",
      "targetVersion",
      "effectiveVersion",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filesystem) {
      self.filesystem = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .capacityGib) {
      self.capacityGib = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountPoint) {
      self.mountPoint = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .perUnitStorageThroughput)
    {
      self.perUnitStorageThroughput = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .gkeSupportEnabled) {
      self.gkeSupportEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateReason) {
      self.stateReason = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .placementPolicy) {
      self.placementPolicy = value
    }
    self.accessRulesOptions = try container.decodeIfPresent(
      AccessRulesOptions.self, forKey: .accessRulesOptions)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.maintenancePolicy = try container.decodeIfPresent(
      MaintenancePolicy.self, forKey: .maintenancePolicy)
    self.upcomingMaintenanceSchedule = try container.decodeIfPresent(
      MaintenanceSchedule.self, forKey: .upcomingMaintenanceSchedule)
    self.dynamicTierOptions = try container.decodeIfPresent(
      DynamicTierOptions.self, forKey: .dynamicTierOptions)
    self.availableVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .availableVersion)
    self.targetVersion = try container.decodeIfPresent(Swift.String.self, forKey: .targetVersion)
    self.effectiveVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .effectiveVersion)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.filesystem, forKey: .filesystem)
    try container.encode(self.capacityGib, forKey: .capacityGib)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.mountPoint, forKey: .mountPoint)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.perUnitStorageThroughput, forKey: .perUnitStorageThroughput)
    try container.encode(self.gkeSupportEnabled, forKey: .gkeSupportEnabled)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.stateReason, forKey: .stateReason)
    try container.encode(self.placementPolicy, forKey: .placementPolicy)
    try container.encodeIfPresent(self.accessRulesOptions, forKey: .accessRulesOptions)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encodeIfPresent(
      self.upcomingMaintenanceSchedule, forKey: .upcomingMaintenanceSchedule)
    try container.encodeIfPresent(self.dynamicTierOptions, forKey: .dynamicTierOptions)
    try container.encodeIfPresent(self.availableVersion, forKey: .availableVersion)
    try container.encodeIfPresent(self.targetVersion, forKey: .targetVersion)
    try container.encodeIfPresent(self.effectiveVersion, forKey: .effectiveVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The possible states of an instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Not set.
    case unspecified
    /// The instance is available for use.
    case active
    /// The instance is being created and is not yet ready for use.
    case creating
    /// The instance is being deleted.
    case deleting
    /// The instance is being upgraded.
    case upgrading
    /// The instance is being repaired.
    case repairing
    /// The instance is stopped.
    case stopped
    /// The instance is being updated.
    @available(*, deprecated)
    case updating
    /// The instance is suspended due to an issue related to Cloud KMS. The
    /// details are available in
    /// [state_reason][google.cloud.lustre.v1.Instance.state_reason].
    ///
    /// [google.cloud.lustre.v1.Instance.state_reason]: <doc:Instance/stateReason>
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .deleting: return 3
      case .upgrading: return 4
      case .repairing: return 5
      case .stopped: return 6
      case .updating: return 7
      case .suspended: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .upgrading: return "UPGRADING"
      case .repairing: return "REPAIRING"
      case .stopped: return "STOPPED"
      case .updating: return "UPDATING"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPGRADING": self = .upgrading
      case "REPAIRING": self = .repairing
      case "STOPPED": self = .stopped
      case "UPDATING": self = .updating
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .upgrading
      case 5: self = .repairing
      case 6: self = .stopped
      case 7: self = .updating
      case 8: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .upgrading: return try container.encode("UPGRADING")
      case .repairing: return try container.encode("REPAIRING")
      case .stopped: return try container.encode("STOPPED")
      case .updating: return try container.encode("UPDATING")
      case .suspended: return try container.encode("SUSPENDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
