// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines a maintenance policy for a resource.
public struct MaintenancePolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The weekly maintenance windows for the instance. Currently
  /// limited to 1 window.
  public var weeklyMaintenanceWindows: [MaintenancePolicy.WeeklyMaintenanceWindow] = []

  /// Optional. The exclusion windows for the instance. Currently limited to 1
  /// window.
  public var maintenanceExclusionWindow: [MaintenancePolicy.MaintenanceExclusionWindow] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MaintenancePolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenancePolicy().with { $0.weeklyMaintenanceWindows = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let weeklyMaintenanceWindows = CodingKeys(stringValue: "weeklyMaintenanceWindows")
    static let maintenanceExclusionWindow = CodingKeys(stringValue: "maintenanceExclusionWindow")

    static let _knownKeys: Set<Swift.String> = [
      "weeklyMaintenanceWindows",
      "maintenanceExclusionWindow",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [MaintenancePolicy.WeeklyMaintenanceWindow].self, forKey: .weeklyMaintenanceWindows)
    {
      self.weeklyMaintenanceWindows = value
    }
    if let value = try container.decodeIfPresent(
      [MaintenancePolicy.MaintenanceExclusionWindow].self, forKey: .maintenanceExclusionWindow)
    {
      self.maintenanceExclusionWindow = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.weeklyMaintenanceWindows, forKey: .weeklyMaintenanceWindows)
    try container.encode(self.maintenanceExclusionWindow, forKey: .maintenanceExclusionWindow)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Weekly time window in which maintenance updates may occur.
  /// Duration of the window is currently fixed at 1 hour.
  /// Time zone is UTC.
  public struct WeeklyMaintenanceWindow: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Day of the week for the maintenance window.
    public var dayOfWeek: GoogleType.DayOfWeek = GoogleType.DayOfWeek()

    /// Required. Start time of the maintenance window in UTC time zone.
    public var startTime: GoogleType.TimeOfDay? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WeeklyMaintenanceWindow`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WeeklyMaintenanceWindow().with { $0.dayOfWeek = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dayOfWeek = CodingKeys(stringValue: "dayOfWeek")
      static let startTime = CodingKeys(stringValue: "startTime")

      static let _knownKeys: Set<Swift.String> = [
        "dayOfWeek",
        "startTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(GoogleType.DayOfWeek.self, forKey: .dayOfWeek) {
        self.dayOfWeek = value
      }
      self.startTime = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .startTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dayOfWeek, forKey: .dayOfWeek)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `WeeklyMaintenanceWindow`: `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.WeeklyMaintenanceWindow"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.WeeklyMaintenanceWindow"
    }

    /// Initialize an instance of `WeeklyMaintenanceWindow` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.WeeklyMaintenanceWindow"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `WeeklyMaintenanceWindow` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Exclusion period when maintenance updates should not occur.
  /// An exclusion window can be in either of the following two formats:
  /// * Non-recurring : A full date, with non-zero year, month and day values.
  /// * Recurring : A month and day value, with a zero year.
  /// Time zone is UTC.
  public struct MaintenanceExclusionWindow: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Start date of the exclusion period in UTC time zone. This date
    /// is inclusive.
    public var startDate: GoogleType.Date? = nil

    /// Required. End date of the exclusion period in UTC time zone. This date is
    /// inclusive.
    public var endDate: GoogleType.Date? = nil

    /// Required. Time in UTC when the exclusion window starts on start_date and
    /// ends on end_date. This can be:
    /// * Full time OR
    /// * All zeros for 00:00:00 UTC
    public var time: GoogleType.TimeOfDay? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MaintenanceExclusionWindow`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MaintenanceExclusionWindow().with { $0.startDate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startDate = CodingKeys(stringValue: "startDate")
      static let endDate = CodingKeys(stringValue: "endDate")
      static let time = CodingKeys(stringValue: "time")

      static let _knownKeys: Set<Swift.String> = [
        "startDate",
        "endDate",
        "time",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .startDate)
      self.endDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .endDate)
      self.time = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .time)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startDate, forKey: .startDate)
      try container.encodeIfPresent(self.endDate, forKey: .endDate)
      try container.encodeIfPresent(self.time, forKey: .time)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `MaintenanceExclusionWindow`: `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.MaintenanceExclusionWindow"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.MaintenanceExclusionWindow"
    }

    /// Initialize an instance of `MaintenanceExclusionWindow` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy.MaintenanceExclusionWindow"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `MaintenanceExclusionWindow` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `MaintenancePolicy`: `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy"
  }

  /// Initialize an instance of `MaintenancePolicy` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.MaintenancePolicy"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `MaintenancePolicy` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
