// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a Cloud Storage mirror.
public struct Mirror: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the mirror.
  /// Format:
  /// `projects/{project}/locations/{location}/instances/{instance}/mirrors/{mirror}`
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The URI to a Cloud Storage bucket, or a path within a
  /// bucket, using the format `gs://{BUCKET_NAME}/{OPTIONAL_PATH}/`. If a path
  /// inside the bucket is specified, it must end with a forward slash (`/`).
  public var gcsPath: GcsPath? = nil

  /// Required. Immutable. The Managed Lustre directory to mirror to. Must be an
  /// absolute path starting with `/`, for example `/data` or `/data/subdir`.
  /// Defaults to the root directory, `/`. If the specified directory doesn't
  /// exist, it is created.
  public var lustrePath: LustrePath? = nil

  /// Required. Immutable. Represents the direction of the mirror.
  public var direction: Mirror.Direction = Mirror.Direction()

  /// Optional. If `true`, files are not deleted from Managed Lustre when the
  /// source files are deleted from Cloud Storage. Default is `false`.
  public var deletedFilesRetained: Swift.Bool = Swift.Bool()

  /// Optional. Description of the mirror.
  public var description: Swift.String = Swift.String()

  /// Optional. Labels to apply to the mirror.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. [Output only] Create time stamp.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update time stamp.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Unique ID of the resource.
  public var uid: Swift.String = Swift.String()

  /// Output only. [Output only] The current state of the mirror.
  public var state: Mirror.State = Mirror.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Mirror`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Mirror().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let gcsPath = CodingKeys(stringValue: "gcsPath")
    static let lustrePath = CodingKeys(stringValue: "lustrePath")
    static let direction = CodingKeys(stringValue: "direction")
    static let deletedFilesRetained = CodingKeys(stringValue: "deletedFilesRetained")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let uid = CodingKeys(stringValue: "uid")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "gcsPath",
      "lustrePath",
      "direction",
      "deletedFilesRetained",
      "description",
      "labels",
      "createTime",
      "updateTime",
      "uid",
      "state",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.gcsPath = try container.decodeIfPresent(GcsPath.self, forKey: .gcsPath)
    self.lustrePath = try container.decodeIfPresent(LustrePath.self, forKey: .lustrePath)
    if let value = try container.decodeIfPresent(Mirror.Direction.self, forKey: .direction) {
      self.direction = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deletedFilesRetained) {
      self.deletedFilesRetained = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Mirror.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.gcsPath, forKey: .gcsPath)
    try container.encodeIfPresent(self.lustrePath, forKey: .lustrePath)
    try container.encode(self.direction, forKey: .direction)
    try container.encode(self.deletedFilesRetained, forKey: .deletedFilesRetained)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the direction of the mirror.
  /// This enum expects to be extended in future with new mirror types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Direction: Codable, Equatable, Hashable, Sendable {
    /// Invalid value.
    case unspecified
    /// Mirror from Cloud Storage to Lustre.
    case fromCloudStorage
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fromCloudStorage: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DIRECTION_UNSPECIFIED"
      case .fromCloudStorage: return "FROM_CLOUD_STORAGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Direction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DIRECTION_UNSPECIFIED": self = .unspecified
      case "FROM_CLOUD_STORAGE": self = .fromCloudStorage
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Direction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fromCloudStorage
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DIRECTION_UNSPECIFIED")
      case .fromCloudStorage: return try container.encode("FROM_CLOUD_STORAGE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of the mirror.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// State is unspecified.
    case unspecified
    /// The mirror resource is being created.
    case creating
    /// The initial sync is copying existing objects from Cloud Storage.
    case initialSync
    /// The mirror is being deleted.
    case deleting
    /// The mirror is synchronizing changes as they occur.
    case active
    /// Synchronization is paused because the file system is close to capacity.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .initialSync: return 2
      case .deleting: return 3
      case .active: return 4
      case .suspended: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .initialSync: return "INITIAL_SYNC"
      case .deleting: return "DELETING"
      case .active: return "ACTIVE"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "INITIAL_SYNC": self = .initialSync
      case "DELETING": self = .deleting
      case "ACTIVE": self = .active
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .initialSync
      case 3: self = .deleting
      case 4: self = .active
      case 5: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .initialSync: return try container.encode("INITIAL_SYNC")
      case .deleting: return try container.encode("DELETING")
      case .active: return try container.encode("ACTIVE")
      case .suspended: return try container.encode("SUSPENDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.Mirror"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
