// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for requesting to reschedule a maintenance event for a specific
/// instance.
public struct RescheduleMaintenanceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Format:
  /// projects/{project}/locations/{location}/instances/{instance}
  public var name: Swift.String = Swift.String()

  /// Required. The desired reschedule settings.
  public var reschedule: RescheduleMaintenanceRequest.Reschedule? = nil

  /// Optional. A unique identifier for this request. A random UUID is
  /// recommended. This request is only idempotent if a `request_id` is provided.
  public var requestId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RescheduleMaintenanceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RescheduleMaintenanceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let reschedule = CodingKeys(stringValue: "reschedule")
    static let requestId = CodingKeys(stringValue: "requestId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "reschedule",
      "requestId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.reschedule = try container.decodeIfPresent(
      RescheduleMaintenanceRequest.Reschedule.self, forKey: .reschedule)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.reschedule, forKey: .reschedule)
    try container.encode(self.requestId, forKey: .requestId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The desired reschedule settings.
  public struct Reschedule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The type of rescheduling.
    public var rescheduleType: RescheduleMaintenanceRequest.RescheduleType =
      RescheduleMaintenanceRequest.RescheduleType()

    /// Optional. Required if reschedule_type is BY_TIME. Timestamp when the
    /// maintenance shall be rescheduled to. This time must be within
    /// 28 days of the original scheduled maintenance start time.
    public var scheduleTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Reschedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Reschedule().with { $0.rescheduleType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let rescheduleType = CodingKeys(stringValue: "rescheduleType")
      static let scheduleTime = CodingKeys(stringValue: "scheduleTime")

      static let _knownKeys: Set<Swift.String> = [
        "rescheduleType",
        "scheduleTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        RescheduleMaintenanceRequest.RescheduleType.self, forKey: .rescheduleType)
      {
        self.rescheduleType = value
      }
      self.scheduleTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .scheduleTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.rescheduleType, forKey: .rescheduleType)
      try container.encodeIfPresent(self.scheduleTime, forKey: .scheduleTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Reschedule`: `"type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest.Reschedule"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest.Reschedule"
    }

    /// Initialize an instance of `Reschedule` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest.Reschedule"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Reschedule` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of rescheduling event. More reschedule types may be added in the
  /// future.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum RescheduleType: Codable, Equatable, Hashable, Sendable {
    /// Unspecified schedule type.
    case unspecified
    /// Apply update immediately
    case immediate
    /// Reschedule to the next available window.
    case nextAvailableWindow
    /// Reschedule to a specific time.
    case byTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .immediate: return 1
      case .nextAvailableWindow: return 2
      case .byTime: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESCHEDULE_TYPE_UNSPECIFIED"
      case .immediate: return "IMMEDIATE"
      case .nextAvailableWindow: return "NEXT_AVAILABLE_WINDOW"
      case .byTime: return "BY_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RescheduleType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESCHEDULE_TYPE_UNSPECIFIED": self = .unspecified
      case "IMMEDIATE": self = .immediate
      case "NEXT_AVAILABLE_WINDOW": self = .nextAvailableWindow
      case "BY_TIME": self = .byTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RescheduleType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .immediate
      case 2: self = .nextAvailableWindow
      case 3: self = .byTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RESCHEDULE_TYPE_UNSPECIFIED")
      case .immediate: return try container.encode("IMMEDIATE")
      case .nextAvailableWindow: return try container.encode("NEXT_AVAILABLE_WINDOW")
      case .byTime: return try container.encode("BY_TIME")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `RescheduleMaintenanceRequest`: `"type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest"
  }

  /// Initialize an instance of `RescheduleMaintenanceRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.RescheduleMaintenanceRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RescheduleMaintenanceRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
