// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A collection of counters that report the progress of a transfer operation.
public struct TransferCounters: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Objects found in the data source that are scheduled to be transferred,
  /// excluding any that are filtered based on object conditions or skipped due
  /// to sync.
  public var foundObjectsCount: Swift.Int64 = Swift.Int64()

  /// Total number of bytes found in the data source that are scheduled to be
  /// transferred, excluding any that are filtered based on object conditions or
  /// skipped due to sync.
  public var bytesFoundCount: Swift.Int64 = Swift.Int64()

  /// Objects in the data source that are not transferred because they already
  /// exist in the data destination.
  public var objectsSkippedCount: Swift.Int64 = Swift.Int64()

  /// Bytes in the data source that are not transferred because they already
  /// exist in the data destination.
  public var bytesSkippedCount: Swift.Int64 = Swift.Int64()

  /// Objects that are copied to the data destination.
  public var objectsCopiedCount: Swift.Int64 = Swift.Int64()

  /// Bytes that are copied to the data destination.
  public var bytesCopiedCount: Swift.Int64 = Swift.Int64()

  /// Output only. Objects that are failed to write to the data destination.
  public var objectsFailedCount: Swift.Int64 = Swift.Int64()

  /// Output only. Bytes that are failed to write to the data destination.
  public var bytesFailedCount: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferCounters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferCounters().with { $0.foundObjectsCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let foundObjectsCount = CodingKeys(stringValue: "foundObjectsCount")
    static let bytesFoundCount = CodingKeys(stringValue: "bytesFoundCount")
    static let objectsSkippedCount = CodingKeys(stringValue: "objectsSkippedCount")
    static let bytesSkippedCount = CodingKeys(stringValue: "bytesSkippedCount")
    static let objectsCopiedCount = CodingKeys(stringValue: "objectsCopiedCount")
    static let bytesCopiedCount = CodingKeys(stringValue: "bytesCopiedCount")
    static let objectsFailedCount = CodingKeys(stringValue: "objectsFailedCount")
    static let bytesFailedCount = CodingKeys(stringValue: "bytesFailedCount")

    static let _knownKeys: Set<Swift.String> = [
      "foundObjectsCount",
      "bytesFoundCount",
      "objectsSkippedCount",
      "bytesSkippedCount",
      "objectsCopiedCount",
      "bytesCopiedCount",
      "objectsFailedCount",
      "bytesFailedCount",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .foundObjectsCount) {
      self.foundObjectsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .bytesFoundCount) {
      self.bytesFoundCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .objectsSkippedCount) {
      self.objectsSkippedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .bytesSkippedCount) {
      self.bytesSkippedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .objectsCopiedCount) {
      self.objectsCopiedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .bytesCopiedCount) {
      self.bytesCopiedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .objectsFailedCount) {
      self.objectsFailedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .bytesFailedCount) {
      self.bytesFailedCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.foundObjectsCount, forKey: .foundObjectsCount)
    try container.encode(self.bytesFoundCount, forKey: .bytesFoundCount)
    try container.encode(self.objectsSkippedCount, forKey: .objectsSkippedCount)
    try container.encode(self.bytesSkippedCount, forKey: .bytesSkippedCount)
    try container.encode(self.objectsCopiedCount, forKey: .objectsCopiedCount)
    try container.encode(self.bytesCopiedCount, forKey: .bytesCopiedCount)
    try container.encode(self.objectsFailedCount, forKey: .objectsFailedCount)
    try container.encode(self.bytesFailedCount, forKey: .bytesFailedCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.TransferCounters"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
