// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents the metadata of the long-running transfer operation.
public struct TransferOperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The progress of the transfer operation.
  public var counters: TransferCounters? = nil

  /// Output only. The type of transfer occurring.
  public var transferType: TransferType = TransferType()

  /// Output only. Error summary about the transfer operation
  public var errorSummaries: [ErrorSummary] = []

  /// The source of transfer operation.
  public var source: SourceOneOf? = nil

  /// The destination of transfer operation.
  public var destination: DestinationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferOperationMetadata().with { $0.sourceLustrePath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceLustrePath = CodingKeys(stringValue: "sourceLustrePath")
    static let sourceGcsPath = CodingKeys(stringValue: "sourceGcsPath")
    static let destinationGcsPath = CodingKeys(stringValue: "destinationGcsPath")
    static let destinationLustrePath = CodingKeys(stringValue: "destinationLustrePath")
    static let counters = CodingKeys(stringValue: "counters")
    static let transferType = CodingKeys(stringValue: "transferType")
    static let errorSummaries = CodingKeys(stringValue: "errorSummaries")

    static let _knownKeys: Set<Swift.String> = [
      "sourceLustrePath",
      "sourceGcsPath",
      "destinationGcsPath",
      "destinationLustrePath",
      "counters",
      "transferType",
      "errorSummaries",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.counters = try container.decodeIfPresent(TransferCounters.self, forKey: .counters)
    if let value = try container.decodeIfPresent(TransferType.self, forKey: .transferType) {
      self.transferType = value
    }
    if let value = try container.decodeIfPresent([ErrorSummary].self, forKey: .errorSummaries) {
      self.errorSummaries = value
    }

    var source: SourceOneOf? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let sourceLustrePath = try container.decodeIfPresent(
      LustrePath.self, forKey: .sourceLustrePath)
    {
      try sourceCheckAndSet(.sourceLustrePath(sourceLustrePath))
    }
    if let sourceGcsPath = try container.decodeIfPresent(GcsPath.self, forKey: .sourceGcsPath) {
      try sourceCheckAndSet(.sourceGcsPath(sourceGcsPath))
    }
    self.source = source

    var destination: DestinationOneOf? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let destinationGcsPath = try container.decodeIfPresent(
      GcsPath.self, forKey: .destinationGcsPath)
    {
      try destinationCheckAndSet(.destinationGcsPath(destinationGcsPath))
    }
    if let destinationLustrePath = try container.decodeIfPresent(
      LustrePath.self, forKey: .destinationLustrePath)
    {
      try destinationCheckAndSet(.destinationLustrePath(destinationLustrePath))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.counters, forKey: .counters)
    try container.encode(self.transferType, forKey: .transferType)
    try container.encode(self.errorSummaries, forKey: .errorSummaries)

    if let choice = self.source {
      switch choice {
      case .sourceLustrePath(let value):
        try container.encode(value, forKey: .sourceLustrePath)
      case .sourceGcsPath(let value):
        try container.encode(value, forKey: .sourceGcsPath)
      }
    }

    if let choice = self.destination {
      switch choice {
      case .destinationGcsPath(let value):
        try container.encode(value, forKey: .destinationGcsPath)
      case .destinationLustrePath(let value):
        try container.encode(value, forKey: .destinationLustrePath)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source of transfer operation.
  public enum SourceOneOf: Codable, Equatable, Sendable {
    /// Output only. Lustre source.
    indirect case sourceLustrePath(LustrePath)
    /// Output only. Cloud Storage source.
    indirect case sourceGcsPath(GcsPath)
  }

  /// The destination of transfer operation.
  public enum DestinationOneOf: Codable, Equatable, Sendable {
    /// Output only. Cloud Storage destination.
    indirect case destinationGcsPath(GcsPath)
    /// Output only. Lustre destination.
    indirect case destinationLustrePath(LustrePath)
  }

  /// The type URL for `TransferOperationMetadata`: `"type.googleapis.com/google.cloud.lustre.v1.TransferOperationMetadata"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.TransferOperationMetadata"
  }

  /// Initialize an instance of `TransferOperationMetadata` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.lustre.v1.TransferOperationMetadata"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `TransferOperationMetadata` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
