// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for UpdateMirror.
public struct UpdateMirrorRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Mirror to update. The mirror's `name` field is used to identify
  /// the mirror to update, in the format:
  /// `projects/{project}/locations/{location}/instances/{instance}/mirrors/{mirror}`
  public var mirror: Mirror? = nil

  /// Optional. Fields specified in the update_mask are relative to the resource,
  /// not the full request. A field will be overwritten if it is in the mask. If
  /// no mask is provided then all fields present in the request are overwritten.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// Optional. The unique ID to identify requests. Specify a unique request ID
  /// so that if you must retry your request, the server will know to ignore
  /// the request if it has already been completed. The server guarantees that a
  /// request doesn't result in the same update request being executed for at
  /// least 60 minutes.
  ///
  /// For example, consider a situation where you make an initial request and the
  /// request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request.
  ///
  /// The request ID must be a valid UUID version 4 with the exception that zero
  /// UUID is not supported (`00000000-0000-0000-0000-000000000000`).
  /// This request is only idempotent if a `request_id` is provided.
  public var requestId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateMirrorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateMirrorRequest().with { $0.mirror = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mirror = CodingKeys(stringValue: "mirror")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let requestId = CodingKeys(stringValue: "requestId")

    static let _knownKeys: Set<Swift.String> = [
      "mirror",
      "updateMask",
      "requestId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.mirror = try container.decodeIfPresent(Mirror.self, forKey: .mirror)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.mirror, forKey: .mirror)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.requestId, forKey: .requestId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.UpdateMirrorRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
